on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

name: run tests
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Installing dependencies
        run: go mod vendor
      - name: Run tests
        env:
          ROTEIRO_DISTANCEESTIMATOR_GOOGLEMAPS_ENABLED: false
          ROTEIRO_DISTANCEESTIMATOR_GOOGLEMAPS_APIKEY: ${{ secrets.ROTEIRO_DISTANCEESTIMATOR_GOOGLEMAPS_APIKEY }}
          ROTEIRO_SERVER_PORT: 8080
          ROTEIRO_SERVER_MODE: debug
          ROTEIRO_LOG_LEVEL: info
        run: go test -mod=vendor -tags=integration -race -p 1 ./...

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Installing dependencies
        run: go mod vendor
      - name: Calc coverage
        env:
          ROTEIRO_DISTANCEESTIMATOR_GOOGLEMAPS_ENABLED: false
          ROTEIRO_DISTANCEESTIMATOR_GOOGLEMAPS_APIKEY: ${{ secrets.ROTEIRO_DISTANCEESTIMATOR_GOOGLEMAPS_APIKEY }}
          ROTEIRO_SERVER_PORT: 8080
          ROTEIRO_SERVER_MODE: debug
          ROTEIRO_LOG_LEVEL: info
        run: go test -mod=vendor -covermode=count -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
